[package]
name = "testct"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1" }
base64 = { version = "0.22" }
sct = { version = "0.7" }
x509-parser = { version = "0.17" }
x509-cert = { version = "0.2", features = ["hazmat"] }
serde_json = { version = "1.0" }